import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  status: DS.attr('organization-status'),
  level: DS.attr('organization-level'),
  kind: DS.attr('organization-kind'),
  date: DS.attr(),
  location: DS.attr('string'),
  website: DS.attr('string'),
  facebook: DS.attr('string'),
  twitter: DS.attr('string'),
  email: DS.attr('string'),
  phone: DS.attr('string'),
  picture: DS.attr('string'),
  description: DS.attr('string'),
  short_name: DS.attr('string'),
  long_name: DS.attr('string'),
  parent: DS.belongsTo('organization', {inverse: 'children', async: true}),
  children: DS.hasMany('organization', {inverse: 'parent', async: true}),
  conventions: DS.hasMany('convention', {async: true}),
  awards: DS.hasMany('award', {async: true}),
  chapters: DS.hasMany('chapter', {async: true}),
  judges: DS.hasMany('judge', {async: true}),
  groups: DS.hasMany('group', {async: true}),
  performers: DS.hasMany('performer', {async: true}),
  participants: DS.hasMany('participant', {async: true}),
  sessions: DS.hasMany('session', {async: true}),
});
